zephyr: vcp: Add VCP tests
auto-pts/auto-pts pull request #1000
Opened 2023-09-14 10:18 UTC by piotrnarajowski

Adding support for VCP volume controler tests

2023-09-14 10:21 UTC, piotrnarajowski commented
@KKopyscinski

2023-09-15 12:59 UTC, sjanc commented on doc/btp_vcp.txt
> +		Command parameters:     Volume (1 octet)
nitpick: address first

2023-09-15 13:05 UTC, piotrnarajowski commented on doc/btp_vcp.txt
> +		Command parameters:     Volume (1 octet)
Fixed

2023-09-29 09:37 UTC, mkasenberg requested changes

2023-09-29 09:37 UTC, mkasenberg commented on autopts/ptsprojects/zephyr/vcp.py
> +    #     r"C:\Program Files\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_MICP_db")
leftover

2023-09-29 09:37 UTC, mkasenberg commented on autopts/pybtp/btp/aics.py
>      description = struct.unpack_from(f'<{len(data) - struct.calcsize(fmt) - 1}s', data, offset=struct.calcsize(fmt))
```suggestion
    description = struct.unpack_from(f'<{len(data) - fmt_size - 1}s', data, offset=fmt_size)
```

2023-09-29 09:37 UTC, mkasenberg commented on autopts/pybtp/btp/aics.py
>      if len(data) < struct.calcsize(fmt):
```suggestion
    fmt_size = struct.calcsize(fmt)
    if len(data) < fmt_size:
```

2023-09-29 09:37 UTC, mkasenberg commented on autopts/wid/micp.py
> +        return False
```suggestion
    return ev[3] == 2
```
Short the other ones too.

2023-09-29 11:54 UTC, mkasenberg commented
#AutoPTS run zephyr VCP MICP

2023-09-29 11:54 UTC, codecoup-tester commented
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1000#issuecomment-1740767415 after 13:55:59.

2023-09-29 12:31 UTC, codecoup-tester commented
AutoPTS Bot results:
<details><summary>Failed tests</summary>MICP    MICP/CL/SPE/BI-01-C             BTP ERROR</details>
<details><summary>Successful tests</summary>MICP    MICP/CL/CGGIT/CHA/BV-01-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-02-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-03-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-04-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-05-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-06-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-07-C       PASS<br>MICP    MICP/CL/CGGIT/SER/BV-01-C       PASS<br>MICP    MICP/CL/CGGIT/SER/BV-02-C       PASS<br>MICP    MICP/CL/CP/BV-01-C              PASS<br>MICP    MICP/CL/CP/BV-02-C              PASS<br>MICP    MICP/CL/CP/BV-03-C              PASS<br>MICP    MICP/CL/CP/BV-04-C              PASS<br>MICP    MICP/CL/CP/BV-05-C              PASS<br>MICP    MICP/CL/SPE/BI-02-C             PASS<br>MICP    MICP/CL/SPE/BI-03-C             PASS<br>MICP    MICP/CL/SPE/BI-04-C             PASS<br>MICP    MICP/CL/SPE/BI-05-C             PASS<br>MICP    MICP/CL/SPE/BI-06-C             PASS<br>MICP    MICP/CL/SPE/BI-07-C             PASS<br>MICP    MICP/CL/SPE/BI-08-C             PASS<br>MICP    MICP/CL/SPE/BI-09-C             PASS<br>MICP    MICP/CL/SPE/BI-10-C             PASS<br>MICP    MICP/CL/SPE/BI-11-C             PASS<br>MICP    MICP/CL/SPE/BI-12-C             PASS<br>VCP     VCP/VC/AICP/BV-01-C             PASS<br>VCP     VCP/VC/AICP/BV-02-C             PASS<br>VCP     VCP/VC/AICP/BV-03-C             PASS<br>VCP     VCP/VC/AICP/BV-04-C             PASS<br>VCP     VCP/VC/AICP/BV-05-C             PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-01-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-02-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-03-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-04-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-05-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-06-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-07-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-08-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-09-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-10-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-11-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-12-C        PASS<br>VCP     VCP/VC/CGGIT/CHA/BV-13-C        PASS<br>VCP     VCP/VC/CGGIT/SER/BV-01-C        PASS<br>VCP     VCP/VC/CGGIT/SER/BV-02-C        PASS<br>VCP     VCP/VC/CGGIT/SER/BV-03-C        PASS<br>VCP     VCP/VC/SPE/BI-01-C              PASS<br>VCP     VCP/VC/SPE/BI-02-C              PASS<br>VCP     VCP/VC/SPE/BI-03-C              PASS<br>VCP     VCP/VC/SPE/BI-04-C              PASS<br>VCP     VCP/VC/SPE/BI-05-C              PASS<br>VCP     VCP/VC/SPE/BI-06-C              PASS<br>VCP     VCP/VC/SPE/BI-07-C              PASS<br>VCP     VCP/VC/SPE/BI-08-C              PASS<br>VCP     VCP/VC/SPE/BI-09-C              PASS<br>VCP     VCP/VC/SPE/BI-10-C              PASS<br>VCP     VCP/VC/SPE/BI-11-C              PASS<br>VCP     VCP/VC/SPE/BI-12-C              PASS<br>VCP     VCP/VC/SPE/BI-13-C              PASS<br>VCP     VCP/VC/SPE/BI-14-C              PASS<br>VCP     VCP/VC/SPE/BI-15-C              PASS<br>VCP     VCP/VC/SPE/BI-16-C              PASS<br>VCP     VCP/VC/SPE/BI-17-C              PASS<br>VCP     VCP/VC/SPE/BI-18-C              PASS<br>VCP     VCP/VC/SPE/BI-19-C              PASS<br>VCP     VCP/VC/SPE/BI-20-C              PASS<br>VCP     VCP/VC/VCCP/BV-01-C             PASS<br>VCP     VCP/VC/VCCP/BV-02-C             PASS<br>VCP     VCP/VC/VCCP/BV-03-C             PASS<br>VCP     VCP/VC/VCCP/BV-04-C             PASS<br>VCP     VCP/VC/VCCP/BV-05-C             PASS<br>VCP     VCP/VC/VCCP/BV-06-C             PASS<br>VCP     VCP/VC/VCCP/BV-07-C             PASS<br>VCP     VCP/VC/VOCP/BV-01-C             PASS</details>

2023-09-29 12:48 UTC, mkasenberg approved these changes

2023-09-29 12:48 UTC, merged