zephyr: micp & aics: Add BTP event
auto-pts/auto-pts pull request #1002
Opened 2023-09-25 13:30 UTC by piotrnarajowski

Enchance BTP events functionality for MICP and AICS

2023-09-25 13:45 UTC, piotrnarajowski commented
@mkasenberg

2023-09-26 11:48 UTC, piotrnarajowski commented
@sjanc

2023-09-29 09:21 UTC, mkasenberg requested changes

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +        return False
```suggestion
return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +        return False
```suggestion
return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +        return False
```suggestion
return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +                return False
```suggestion
            return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +                return False
```suggestion
            return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +                return False
```suggestion
            return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +                return False
```suggestion
            return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +                return False
```suggestion
            return False
```

2023-09-29 09:21 UTC, mkasenberg commented on autopts/wid/micp.py
> +                return False
```suggestion
            return False
```

2023-09-29 11:29 UTC, mkasenberg approved these changes

2023-09-29 11:29 UTC, merged