zephyr: cas: Added support for testing Common Audio Service
auto-pts/auto-pts pull request #1014
Opened 2023-10-02 07:06 UTC by MSEEHenrik

- Set Member Lock
- Get Member RSI

2023-10-05 10:15 UTC, mkasenberg requested changes

2023-10-05 11:17 UTC, MSEEHenrik commented on autopts/ptsprojects/zephyr/cap.py
> +            "TRUE" if stack.gap.iut_addr_is_random() else "FALSE")),
Strange, I didn't get any exception, but I removed the parameter update.

2023-10-05 11:18 UTC, MSEEHenrik commented on autopts/ptsprojects/zephyr/cas.py
> +            "TRUE" if stack.gap.iut_addr_is_random() else "FALSE")),
Strange, I didn't get any exception, but I removed the parameter update.

2023-10-05 11:18 UTC, MSEEHenrik commented on autopts/wid/cas.py
> +def hdl_wid_20001(_:WIDParams):
Done.

2023-10-05 11:18 UTC, MSEEHenrik commented on autopts/wid/cas.py
> +from autopts.pybtp import btp, defs
Done.

2023-10-05 11:18 UTC, MSEEHenrik commented on autopts/wid/cap.py
> +from enum import IntEnum
Done.

2023-10-05 11:19 UTC, MSEEHenrik commented on autopts/wid/cas.py
> +def hdl_wid_20128(_:WIDParams):
Done.

2023-10-05 11:25 UTC, mkasenberg commented on autopts/ptsprojects/zephyr/cas.py
> +            "TRUE" if stack.gap.iut_addr_is_random() else "FALSE")),
It appears only in autoptsserver logs and does not interrupt running test cases.

2023-10-05 11:26 UTC, mkasenberg approved these changes

2023-10-06 07:27 UTC, sjanc approved these changes

2023-10-06 07:44 UTC, merged