zephyr: Minor test case fixes
auto-pts/auto-pts pull request #1079
Opened 2023-12-14 10:05 UTC by mkasenberg

Fixes BAP/CL/CGGIT/CHA/BV-05-C, BAP/CL/CGGIT/CHA/BV-06-C, PACS/SR/PCU/BV-08-C.

2023-12-14 10:06 UTC, sjanc approved these changes

2023-12-15 08:10 UTC, MariuszSkamra requested changes

2023-12-15 08:10 UTC, MariuszSkamra commented on autopts/wid/pacs.py
> +    EMERGENCY_ALARM = BIT(11)
IMO, those should be placed in  `pybtp/defs.py` just like `PACS_AUDIO_LOCATION_*` definitions

2023-12-19 10:56 UTC, sjanc approved these changes

2023-12-20 13:48 UTC, MariuszSkamra approved these changes

2023-12-21 08:35 UTC, merged