pybtp: btp: event handler
auto-pts/auto-pts pull request #981
Opened 2023-07-26 14:39 UTC by piotrnarajowski

Reducing amount of boilerplate code - event handler functions

2023-07-26 14:52 UTC, piotrnarajowski commented
fixes #955

2023-07-27 12:34 UTC, sjanc approved these changes

2023-07-27 12:41 UTC, MariuszSkamra approved these changes

2023-07-27 12:50 UTC, mkasenberg requested changes

2023-07-27 12:50 UTC, mkasenberg commented on autopts/pybtp/btp/btp.py
> +    }
Please rebase. There is one event missing, the BTP_SERVICE_ID_CORE, added recently.

2023-07-27 13:38 UTC, merged